### ISSUE TITLE
Title icon renders small on Firefox

### ISSUE THREAD

**Issue by michealespinola** [jez500/bender#3]
Here is a screen snip of the default "fas fa-robot" icon: 

<https://i.imgur.com/qXTESbW.png>

The icon seems to render fine on Chromium browsers.

**Comment by jez500** [comment]
Thanks for reporting, will look into a fix. Seems  firefox doesn't like the `zoom` property

**Comment by michealespinola** [comment]
Thanks, I appreciate it. I love the interface so far. It's simple and works very well! 

Images seem to work fine across the board. The only issue I see is with icons on Firefox.

Thanks again for a handy tool!

**Comment by jez500** [comment]
This should be solved in `1.0.3` now https://hub.docker.com/r/jez500/bender/tags

Glad you like :)

**Comment by michealespinola** [comment]
Everything looks full-sized and great. Thank you!
